# Generated by Django 4.0.6 on 2022-07-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order_orderitem_remove_product_carts_delete_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
