# Generated by Django 4.0.6 on 2022-08-04 13:44

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_orderitem_order_date_alter_rating_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=product.models.ProductImage.get_product_dir),
        ),
    ]
