# Generated by Django 4.0.6 on 2022-07-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_is_active_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.CharField(default='.', max_length=400),
            preserve_default=False,
        ),
    ]
