# Generated by Django 4.0.6 on 2022-07-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_vendor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_balance',
            field=models.CharField(default='1000000', max_length=300),
        ),
    ]
