# Generated by Django 4.0.6 on 2022-07-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_balance',
            field=models.CharField(default='10000000', max_length=300),
        ),
    ]
